#	This Makefile is written by Zhiyang Ong for build automation of his boilerplate code.

#	The MIT License (MIT)

#	Copyright (c) <2014> <Zhiyang Ong>

#	Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:

#	The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

#	THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

#	Email address: echo "cukj -wb- 23wU4X5M589 TROJANS cqkH wiuz2y 0f Mw Stanford" | awk '{ sub("23wU4X5M589","F.d_c_b. ") sub("Stanford","d0mA1n"); print $5, $2, $8; for (i=1; i<=1; i++) print "6\b"; print $9, $7, $6 }' | sed y/kqcbuHwM62z/gnotrzadqmC/ | tr 'q' ' ' | tr -d [:cntrl:] | tr -d 'ir' | tr y "\n"		Don't compromise my computing accounts. You have been warned.









# Makefile for a library of boilerplate code for my C++ -based software projects.
# @author Zhiyang Ong
#
# Project Name: lamiera-per-caldaie

# =============================================================

# Definition of macro flags...
# IMPORTANT NOTE
# Makefile is written for Mac OS X 10.10.5, running on 2.6 GHz Intel Core i7.


# IMPORTANT:: Paths to be modified!!!
# Benchmark directory, relative from the working directory for Lamiera-per-caldaie
BENCHMARKS=	./benchmarks/
SOURCE=		hw4_q1.mod








# Solvers...
#	GNU Linear Programming Kit package, GLPK
GLPK=		glpsol
#	Flags for GLPK
PRIMAL=		--primal	# Primal of mathematical programming problem.
DUAL=		--dual		# Dual of mathematical programming problem.
IPFILES=	-m			# Input file(s) for linear or mixed-integer programming.









# =============================================================

# Definition of Target Rules
# Use a FOR loop to sweep through the list of benchmarks when
#	the parse is ready, and do regression testing when the router
#	is done.

########################################################################
# BUILD THE SOFTWARE	--	FIX THIS!!!
########################################################################
# Build and test the latest software build 







########################################################################
# TEST THE SOFTWARE: UNIT, MODULE, INTEGRATION, AND REGRESSION TESTING
########################################################################
# Build and test the latest software build.

test:
	@echo + + + + + + + + + + + + + + + + + + + + + + + + + + +
	@echo + + + + + + + + + + + + + + + + + + + + + + + + + + +
	@echo + + + + + + + + + + + + + + + + + + + + + + + + + + +
	$(DATE)
	@echo === GNU Linear Programming Kit package, GLPK.
	@echo === Call the GLPK solver package
	$(GLPK)	$(PRIMAL)	$(IPFILES)$(SOURCE)
























